In [1]:
x = range(70)

In [2]:
x

range(0, 70)

In [3]:
for i in x:
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69

In [4]:
x = range(10,70)
for i in x:
    print(i)

10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69

In [5]:
x = range(10,70,5)
for i in x:
    print(i)

10
15
20
25
30
35
40
45
50
55
60
65

In [6]:
x = range(70,10,-4)
for i in x:
    print(i)

70
66
62
58
54
50
46
42
38
34
30
26
22
18
14

In [8]:
import array as ar

In [10]:
a = ar.array('i',[1,2,3,4])

In [11]:
a

array('i', [1, 2, 3, 4])

In [14]:
a = ar.array("f" ,[1.8,2,3,4,5])

In [15]:
a

array('f', [1.7999999523162842, 2.0, 3.0, 4.0, 5.0])

In [17]:
dic={
    'varsity' : ' National University',
    'Dep' : ' Bachelor of arts '
}

In [18]:
dic

{'varsity': ' National University', 'Dep': ' Bachelor of arts '}

In [19]:
type(dic)

dict

In [21]:
dic.keys()

dict_keys(['varsity', 'Dep'])

In [22]:
dic.values()

dict_values([' National University', ' Bachelor of arts '])

In [23]:
import pandas as pd
import numpy as np

In [34]:
df = pd.read_csv('annual-enterprise-survey-2023-financial-year-provisional.csv')
df.head(10)

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2023,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,930995,ANZSIC06 divisions A-S (excluding classes K633...
1,2023,Level 1,99999,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,821630,ANZSIC06 divisions A-S (excluding classes K633...
2,2023,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,84354,ANZSIC06 divisions A-S (excluding classes K633...
3,2023,Level 1,99999,All industries,Dollars (millions),H07,Non-operating income,Financial performance,25010,ANZSIC06 divisions A-S (excluding classes K633...
4,2023,Level 1,99999,All industries,Dollars (millions),H08,Total expenditure,Financial performance,832964,ANZSIC06 divisions A-S (excluding classes K633...
5,2023,Level 1,99999,All industries,Dollars (millions),H09,Interest and donations,Financial performance,55267,ANZSIC06 divisions A-S (excluding classes K633...
6,2023,Level 1,99999,All industries,Dollars (millions),H10,Indirect taxes,Financial performance,7426,ANZSIC06 divisions A-S (excluding classes K633...
7,2023,Level 1,99999,All industries,Dollars (millions),H11,Depreciation,Financial performance,30814,ANZSIC06 divisions A-S (excluding classes K633...
8,2023,Level 1,99999,All industries,Dollars (millions),H12,Salaries and wages paid,Financial performance,147663,ANZSIC06 divisions A-S (excluding classes K633...
9,2023,Level 1,99999,All industries,Dollars (millions),H13,Redundancy and severance,Financial performance,269,ANZSIC06 divisions A-S (excluding classes K633...

In [32]:
import pandas as pd 
df = pd.read_csv('annual-enterprise-survey-2023-financial-year-provisional.csv')
df.head(15)

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2023,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,930995,ANZSIC06 divisions A-S (excluding classes K633...
1,2023,Level 1,99999,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,821630,ANZSIC06 divisions A-S (excluding classes K633...
2,2023,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,84354,ANZSIC06 divisions A-S (excluding classes K633...
3,2023,Level 1,99999,All industries,Dollars (millions),H07,Non-operating income,Financial performance,25010,ANZSIC06 divisions A-S (excluding classes K633...
4,2023,Level 1,99999,All industries,Dollars (millions),H08,Total expenditure,Financial performance,832964,ANZSIC06 divisions A-S (excluding classes K633...
5,2023,Level 1,99999,All industries,Dollars (millions),H09,Interest and donations,Financial performance,55267,ANZSIC06 divisions A-S (excluding classes K633...
6,2023,Level 1,99999,All industries,Dollars (millions),H10,Indirect taxes,Financial performance,7426,ANZSIC06 divisions A-S (excluding classes K633...
7,2023,Level 1,99999,All industries,Dollars (millions),H11,Depreciation,Financial performance,30814,ANZSIC06 divisions A-S (excluding classes K633...
8,2023,Level 1,99999,All industries,Dollars (millions),H12,Salaries and wages paid,Financial performance,147663,ANZSIC06 divisions A-S (excluding classes K633...
9,2023,Level 1,99999,All industries,Dollars (millions),H13,Redundancy and severance,Financial performance,269,ANZSIC06 divisions A-S (excluding classes K633...
10,2023,Level 1,99999,All industries,Dollars (millions),H14,Salaries and wages to self employed commission...,Financial performance,1639,ANZSIC06 divisions A-S (excluding classes K633...
11,2023,Level 1,99999,All industries,Dollars (millions),H19,Purchases and other operating expenses,Financial performance,566979,ANZSIC06 divisions A-S (excluding classes K633...
12,2023,Level 1,99999,All industries,Dollars (millions),H20,Non-operating expenses,Financial performance,23176,ANZSIC06 divisions A-S (excluding classes K633...
13,2023,Level 1,99999,All industries,Dollars (millions),H21,Opening stocks,Financial performance,80778,ANZSIC06 divisions A-S (excluding classes K633...
14,2023,Level 1,99999,All industries,Dollars (millions),H22,Closing stocks,Financial performance,88197,ANZSIC06 divisions A-S (excluding classes K633...

In [36]:
df.shape

(50985, 10)

In [37]:
df.info

<bound method DataFrame.info of        Year Industry_aggregation_NZSIOC Industry_code_NZSIOC  \
0      2023                     Level 1                99999
1      2023                     Level 1                99999
2      2023                     Level 1                99999
3      2023                     Level 1                99999
4      2023                     Level 1                99999
...     ...                         ...                  ...
50980  2013                     Level 3                 ZZ11
50981  2013                     Level 3                 ZZ11
50982  2013                     Level 3                 ZZ11
50983  2013                     Level 3                 ZZ11
50984  2013                     Level 3                 ZZ11

             Industry_name_NZSIOC               Units Variable_code  \
0                  All industries  Dollars (millions)           H01
1                  All industries  Dollars (millions)           H04
2                  All industries  Dollars (millions)           H05
3                  All industries  Dollars (millions)           H07
4                  All industries  Dollars (millions)           H08
...                           ...                 ...           ...
50980  Food product manufacturing          Percentage           H37
50981  Food product manufacturing          Percentage           H38
50982  Food product manufacturing          Percentage           H39
50983  Food product manufacturing          Percentage           H40
50984  Food product manufacturing          Percentage           H41

                                         Variable_name      Variable_category  \
0                                         Total income  Financial performance
1      Sales, government funding, grants and subsidies  Financial performance
2                    Interest, dividends and donations  Financial performance
3                                 Non-operating income  Financial performance
4                                    Total expenditure  Financial performance
...                                                ...                    ...
50980                                      Quick ratio       Financial ratios
50981              Margin on sales of goods for resale       Financial ratios
50982                                 Return on equity       Financial ratios
50983                           Return on total assets       Financial ratios
50984                            Liabilities structure       Financial ratios

        Value                             Industry_code_ANZSIC06
0      930995  ANZSIC06 divisions A-S (excluding classes K633...
1      821630  ANZSIC06 divisions A-S (excluding classes K633...
2       84354  ANZSIC06 divisions A-S (excluding classes K633...
3       25010  ANZSIC06 divisions A-S (excluding classes K633...
4      832964  ANZSIC06 divisions A-S (excluding classes K633...
...       ...                                                ...
50980      52  ANZSIC06 groups C111, C112, C113, C114, C115, ...
50981      40  ANZSIC06 groups C111, C112, C113, C114, C115, ...
50982      12  ANZSIC06 groups C111, C112, C113, C114, C115, ...
50983       5  ANZSIC06 groups C111, C112, C113, C114, C115, ...
50984      46  ANZSIC06 groups C111, C112, C113, C114, C115, ...

[50985 rows x 10 columns]>